--
-- This code was automatically generated by the B-ASIC toolbox.
-- Code generation timestamp: (2025-11-05 22:58:23.906820)
-- B-ASIC version: 0.1.0.dev825+unknown.g9c5aff44b
-- URL: https://github.com/b-asic-eda/b-asic
--

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
entity in0 is
    port (
        clk : in std_logic;
        schedule_cnt : in unsigned(3 downto 0);
        p_0_in : in std_logic_vector(7 downto 0);
        p_0_out : out signed(7 downto 0)
    );
end entity in0;

architecture rtl of in0 is
    signal res_0 : signed(7 downto 0);

begin
    p_0_out <= res_0;
    res_0 <= resize(signed(p_0_in), 8);

end architecture rtl;

