--
-- This code was automatically generated by the B-ASIC toolbox.
-- Code generation timestamp: (2025-11-08 12:16:37.027358)
-- B-ASIC version: 0.1.0.dev825+unknown.g9c5aff44b
-- URL: https://github.com/b-asic-eda/b-asic
--

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
entity lwdf is
    port (
        clk : in std_logic;
        rst : in std_logic;
        in0_0_in : in std_logic_vector(7 downto 0);
        out0_0_out : out std_logic_vector(7 downto 0)
    );
end entity lwdf;

architecture rtl of lwdf is
    -- Component declaration
    component sym2p0
        port (
            clk : in std_logic;
            schedule_cnt : in unsigned(3 downto 0);
            p_0_in : in signed(7 downto 0);
            p_1_in : in signed(7 downto 0);
            p_0_out : out signed(7 downto 0);
            p_1_out : out signed(7 downto 0)
        );
    end component;
    component sym2p1
        port (
            clk : in std_logic;
            schedule_cnt : in unsigned(3 downto 0);
            p_0_in : in signed(7 downto 0);
            p_1_in : in signed(7 downto 0);
            p_0_out : out signed(7 downto 0);
            p_1_out : out signed(7 downto 0)
        );
    end component;
    component in0
        port (
            clk : in std_logic;
            schedule_cnt : in unsigned(3 downto 0);
            p_0_in : in std_logic_vector(7 downto 0);
            p_0_out : out signed(7 downto 0)
        );
    end component;
    component out0
        port (
            clk : in std_logic;
            schedule_cnt : in unsigned(3 downto 0);
            p_0_in : in signed(7 downto 0);
            p_0_out : out std_logic_vector(7 downto 0)
        );
    end component;
    component memory0
        port (
            clk : in std_logic;
            schedule_cnt : in unsigned(3 downto 0);
            p_0_in : in signed(7 downto 0);
            p_0_out : out signed(7 downto 0)
        );
    end component;
    component memory1
        port (
            clk : in std_logic;
            schedule_cnt : in unsigned(3 downto 0);
            p_0_in : in signed(7 downto 0);
            p_0_out : out signed(7 downto 0)
        );
    end component;
    component memory2
        port (
            clk : in std_logic;
            schedule_cnt : in unsigned(3 downto 0);
            p_0_in : in signed(7 downto 0);
            p_0_out : out signed(7 downto 0)
        );
    end component;
    component memory3
        port (
            clk : in std_logic;
            schedule_cnt : in unsigned(3 downto 0);
            p_0_in : in signed(7 downto 0);
            p_0_out : out signed(7 downto 0)
        );
    end component;
    component memory4
        port (
            clk : in std_logic;
            schedule_cnt : in unsigned(3 downto 0);
            p_0_in : in signed(7 downto 0);
            p_0_out : out signed(7 downto 0)
        );
    end component;
    -- sym2p0 signals
    signal sym2p0_0_in : signed(7 downto 0);
    signal sym2p0_1_in : signed(7 downto 0);
    signal sym2p0_0_out : signed(7 downto 0);
    signal sym2p0_1_out : signed(7 downto 0);
    -- sym2p1 signals
    signal sym2p1_0_in : signed(7 downto 0);
    signal sym2p1_1_in : signed(7 downto 0);
    signal sym2p1_0_out : signed(7 downto 0);
    signal sym2p1_1_out : signed(7 downto 0);
    -- in0 signals
    signal in0_0_out : signed(7 downto 0);
    -- out0 signals
    signal out0_0_in : signed(7 downto 0);
    -- memory0 signals
    signal memory0_0_in : signed(7 downto 0);
    signal memory0_0_out : signed(7 downto 0);
    -- memory1 signals
    signal memory1_0_in : signed(7 downto 0);
    signal memory1_0_out : signed(7 downto 0);
    -- memory2 signals
    signal memory2_0_in : signed(7 downto 0);
    signal memory2_0_out : signed(7 downto 0);
    -- memory3 signals
    signal memory3_0_in : signed(7 downto 0);
    signal memory3_0_out : signed(7 downto 0);
    -- memory4 signals
    signal memory4_0_in : signed(7 downto 0);
    signal memory4_0_out : signed(7 downto 0);
    signal schedule_cnt : unsigned(3 downto 0) := (others => '0');

begin
    -- Component instantiation
    sym2p0_inst: sym2p0
        port map (
            clk => clk,
            schedule_cnt => schedule_cnt,
            p_0_in => sym2p0_0_in,
            p_1_in => sym2p0_1_in,
            p_0_out => sym2p0_0_out,
            p_1_out => sym2p0_1_out
        );
    sym2p1_inst: sym2p1
        port map (
            clk => clk,
            schedule_cnt => schedule_cnt,
            p_0_in => sym2p1_0_in,
            p_1_in => sym2p1_1_in,
            p_0_out => sym2p1_0_out,
            p_1_out => sym2p1_1_out
        );
    in0_inst: in0
        port map (
            clk => clk,
            schedule_cnt => schedule_cnt,
            p_0_in => in0_0_in,
            p_0_out => in0_0_out
        );
    out0_inst: out0
        port map (
            clk => clk,
            schedule_cnt => schedule_cnt,
            p_0_in => out0_0_in,
            p_0_out => out0_0_out
        );
    memory0_inst: memory0
        port map (
            clk => clk,
            schedule_cnt => schedule_cnt,
            p_0_in => memory0_0_in,
            p_0_out => memory0_0_out
        );
    memory1_inst: memory1
        port map (
            clk => clk,
            schedule_cnt => schedule_cnt,
            p_0_in => memory1_0_in,
            p_0_out => memory1_0_out
        );
    memory2_inst: memory2
        port map (
            clk => clk,
            schedule_cnt => schedule_cnt,
            p_0_in => memory2_0_in,
            p_0_out => memory2_0_out
        );
    memory3_inst: memory3
        port map (
            clk => clk,
            schedule_cnt => schedule_cnt,
            p_0_in => memory3_0_in,
            p_0_out => memory3_0_out
        );
    memory4_inst: memory4
        port map (
            clk => clk,
            schedule_cnt => schedule_cnt,
            p_0_in => memory4_0_in,
            p_0_out => memory4_0_out
        );
    -- Schedule counter
    schedule_cnt_proc: process(clk)
    begin
        if rising_edge(clk) then
            if rst = '1' then
                schedule_cnt <= (others => '0');
            else
                if schedule_cnt = 10 then
                    schedule_cnt <= (others => '0');
                else
                    schedule_cnt <= schedule_cnt + 1;
                end if;
            end if;
        end if;
    end process schedule_cnt_proc;
    with schedule_cnt select
        sym2p0_0_in <=
            memory1_0_out when "0000",
            memory2_0_out when "0001",
            memory2_0_out when "0010",
            memory0_0_out when "0011",
            memory2_0_out when "0100",
            memory2_0_out when "0101",
            memory0_0_out when "0110",
            memory2_0_out when "0111",
            memory4_0_out when "1000",
            memory0_0_out when "1001",
            memory0_0_out when "1010",
            (others => '-') when others;

    with schedule_cnt select
        sym2p0_1_in <=
            memory3_0_out when "0000",
            memory1_0_out when "0001",
            memory1_0_out when "0010",
            memory1_0_out when "0011",
            memory3_0_out when "0100",
            memory0_0_out when "0101",
            memory4_0_out when "0110",
            memory0_0_out when "0111",
            memory0_0_out when "1000",
            memory1_0_out when "1001",
            memory1_0_out when "1010",
            (others => '-') when others;

    with schedule_cnt select
        sym2p1_0_in <=
            memory0_0_out when "0000",
            memory3_0_out when "0001",
            memory0_0_out when "0010",
            sym2p0_0_out when "0011",
            sym2p1_0_out when "0100",
            memory1_0_out when "0101",
            memory1_0_out when "0110",
            in0_0_out when "0111",
            memory2_0_out when "1000",
            sym2p1_0_out when "1001",
            memory3_0_out when "1010",
            (others => '-') when others;

    with schedule_cnt select
        sym2p1_1_in <=
            memory4_0_out when "0000",
            memory4_0_out when "0001",
            memory3_0_out when "0010",
            memory4_0_out when "0011",
            memory0_0_out when "0100",
            memory3_0_out when "0101",
            memory3_0_out when "0110",
            memory4_0_out when "0111",
            memory1_0_out when "1000",
            memory2_0_out when "1001",
            memory2_0_out when "1010",
            (others => '-') when others;

    with schedule_cnt select
        out0_0_in <=
            sym2p1_0_out when "0001",
            memory4_0_out when "0010",
            memory4_0_out when "1010",
            memory2_0_out when "0000",
            (others => '-') when others;

    with schedule_cnt select
        memory0_0_in <=
            sym2p0_0_out when "0000",
            sym2p1_1_out when "0001",
            sym2p0_1_out when "1010",
            sym2p1_0_out when "1000",
            sym2p1_0_out when "0100",
            sym2p1_0_out when "0101",
            sym2p0_1_out when "0010",
            sym2p0_0_out when "0111",
            (others => '-') when others;

    with schedule_cnt select
        memory1_0_in <=
            sym2p1_1_out when "0000",
            sym2p0_1_out when "0101",
            sym2p0_0_out when "0010",
            sym2p0_1_out when "0001",
            sym2p1_1_out when "1001",
            sym2p1_0_out when "1010",
            sym2p0_1_out when "0110",
            sym2p1_1_out when "0111",
            sym2p1_0_out when "0011",
            (others => '-') when others;

    with schedule_cnt select
        memory2_0_in <=
            sym2p0_1_out when "0000",
            sym2p0_1_out when "0011",
            sym2p0_0_out when "0100",
            sym2p0_0_out when "0001",
            sym2p1_1_out when "0010",
            sym2p0_1_out when "1000",
            sym2p1_0_out when "0111",
            sym2p0_0_out when "0110",
            sym2p0_0_out when "0101",
            (others => '-') when others;

    with schedule_cnt select
        memory3_0_in <=
            sym2p0_0_out when "1001",
            sym2p0_1_out when "0100",
            sym2p1_1_out when "1000",
            sym2p0_0_out when "1010",
            sym2p0_1_out when "0111",
            sym2p1_1_out when "0101",
            sym2p1_1_out when "0110",
            (others => '-') when others;

    with schedule_cnt select
        memory4_0_in <=
            sym2p1_0_out when "0010",
            sym2p1_1_out when "0100",
            sym2p1_0_out when "0110",
            sym2p1_0_out when "0000",
            sym2p1_1_out when "1010",
            sym2p0_1_out when "1001",
            sym2p1_1_out when "0011",
            sym2p0_0_out when "1000",
            (others => '-') when others;

end architecture rtl;


