--
-- This code was automatically generated by the B-ASIC toolbox.
-- Code generation timestamp: (2025-11-08 12:16:37.021194)
-- B-ASIC version: 0.1.0.dev825+unknown.g9c5aff44b
-- URL: https://github.com/b-asic-eda/b-asic
--

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
entity memory1 is
    port (
        clk : in std_logic;
        schedule_cnt : in unsigned(3 downto 0);
        p_0_in : in signed(7 downto 0);
        p_0_out : out signed(7 downto 0)
    );
end entity memory1;

architecture rtl of memory1 is

    -- HDL memory description
    type mem_type is array(0 to 2) of signed(7 downto 0);
    signal memory : mem_type := (others => (others => '0'));
    alias schedule_cnt_adr : unsigned(3 downto 0) is schedule_cnt(3 downto 0);

    -- Memory address generation
    signal read_port_0 : signed(7 downto 0);
    signal read_adr_0 : unsigned(1 downto 0);
    signal read_en_0 : std_logic;
    signal write_port_0 : signed(7 downto 0);
    signal write_adr_0 : unsigned(1 downto 0);
    signal write_en_0 : std_logic;

    -- Address generation multiplexing signals
    signal write_adr_0_0_0 : unsigned(1 downto 0);
    signal write_en_0_0_0 : std_logic;
    signal read_adr_0_0_0 : unsigned(1 downto 0);

begin


    -- Memory
    mem_0_proc: process(clk)
    begin
        if rising_edge(clk) then
            if write_en_0 = '1' then
                memory(to_integer(write_adr_0)) <= write_port_0;
            end if;
        end if;
    end process mem_0_proc;
    read_port_0 <= memory(to_integer(read_adr_0));
    read_adr_0 <= read_adr_0_0_0;
    write_adr_0 <= write_adr_0_0_0;
    write_en_0 <= write_en_0_0_0;
    write_port_0 <= p_0_in;
    p_0_out <= read_port_0;

    --
    -- Memory write address generation
    --
    mem_write_address_proc: process(schedule_cnt_adr)
    begin
            case to_integer(schedule_cnt_adr) is
                -- MemoryVariable(0, <b_asic.port.OutputPort object at 0x7f686c0e1450>, {<b_asic.port.InputPort object at 0x7f686c0e1270>: 2}, 'sym2p4_1.1')
                when 0 =>
                    write_adr_0_0_0 <= to_unsigned(0, write_adr_0_0_0'length);
                    write_en_0_0_0 <= '1';
                -- MemoryVariable(1, <b_asic.port.OutputPort object at 0x7f686c0e11d0>, {<b_asic.port.InputPort object at 0x7f686c0e05f0>: 2}, 'sym2p3_0.1')
                when 1 =>
                    write_adr_0_0_0 <= to_unsigned(1, write_adr_0_0_0'length);
                    write_en_0_0_0 <= '1';
                -- MemoryVariable(2, <b_asic.port.OutputPort object at 0x7f686c0e0780>, {<b_asic.port.InputPort object at 0x7f686c0e0960>: 4}, 'sym2p0_1.0')
                when 2 =>
                    write_adr_0_0_0 <= to_unsigned(0, write_adr_0_0_0'length);
                    write_en_0_0_0 <= '1';
                -- MemoryVariable(3, <b_asic.port.OutputPort object at 0x7f686c0e03c0>, {<b_asic.port.InputPort object at 0x7f686c0e0460>: 2}, 'sym2p8.0')
                when 3 =>
                    write_adr_0_0_0 <= to_unsigned(1, write_adr_0_0_0'length);
                    write_en_0_0_0 <= '1';
                -- MemoryVariable(5, <b_asic.port.OutputPort object at 0x7f686c0e1310>, {<b_asic.port.InputPort object at 0x7f686c0e13b0>: 3}, 'sym2p4_0.1')
                when 5 =>
                    write_adr_0_0_0 <= to_unsigned(1, write_adr_0_0_0'length);
                    write_en_0_0_0 <= '1';
                -- MemoryVariable(6, <b_asic.port.OutputPort object at 0x7f686c0e0690>, {<b_asic.port.InputPort object at 0x7f686c0e1130>: 3}, 'sym2p3_1.1')
                when 6 =>
                    write_adr_0_0_0 <= to_unsigned(0, write_adr_0_0_0'length);
                    write_en_0_0_0 <= '1';
                -- MemoryVariable(7, <b_asic.port.OutputPort object at 0x7f686c0e0910>, {<b_asic.port.InputPort object at 0x7f686c0e0730>: 3}, 'sym2p0_0.1')
                when 7 =>
                    write_adr_0_0_0 <= to_unsigned(2, write_adr_0_0_0'length);
                    write_en_0_0_0 <= '1';
                -- MemoryVariable(9, <b_asic.port.OutputPort object at 0x7f686c0e0a50>, {<b_asic.port.InputPort object at 0x7f686c0e0af0>: 3}, 'sym2p1_1.1')
                when 9 =>
                    write_adr_0_0_0 <= to_unsigned(1, write_adr_0_0_0'length);
                    write_en_0_0_0 <= '1';
                -- MemoryVariable(10, <b_asic.port.OutputPort object at 0x7f686c133980>, {<b_asic.port.InputPort object at 0x7f686c133a20>: 1}, 'sym2p0.0')
                when 10 =>
                    write_adr_0_0_0 <= to_unsigned(0, write_adr_0_0_0'length);
                    write_en_0_0_0 <= '1';
                when others =>
                    write_adr_0_0_0 <= (others => '-');
                    write_en_0_0_0 <= '0';
            end case;
    end process mem_write_address_proc;

    --
    -- Memory read address generation
    --
    mem_read_address_proc: process(schedule_cnt_adr)
    begin
            case to_integer(schedule_cnt_adr) is
                -- MemoryVariable(10, <b_asic.port.OutputPort object at 0x7f686c133980>, {<b_asic.port.InputPort object at 0x7f686c133a20>: 1}, 'sym2p0.0')
                when 0 =>
                    read_adr_0_0_0 <= to_unsigned(0, write_adr_0_0_0'length);
                -- MemoryVariable(9, <b_asic.port.OutputPort object at 0x7f686c0e0a50>, {<b_asic.port.InputPort object at 0x7f686c0e0af0>: 3}, 'sym2p1_1.1')
                when 1 =>
                    read_adr_0_0_0 <= to_unsigned(1, write_adr_0_0_0'length);
                -- MemoryVariable(0, <b_asic.port.OutputPort object at 0x7f686c0e1450>, {<b_asic.port.InputPort object at 0x7f686c0e1270>: 2}, 'sym2p4_1.1')
                when 2 =>
                    read_adr_0_0_0 <= to_unsigned(0, write_adr_0_0_0'length);
                -- MemoryVariable(1, <b_asic.port.OutputPort object at 0x7f686c0e11d0>, {<b_asic.port.InputPort object at 0x7f686c0e05f0>: 2}, 'sym2p3_0.1')
                when 3 =>
                    read_adr_0_0_0 <= to_unsigned(1, write_adr_0_0_0'length);
                -- MemoryVariable(3, <b_asic.port.OutputPort object at 0x7f686c0e03c0>, {<b_asic.port.InputPort object at 0x7f686c0e0460>: 2}, 'sym2p8.0')
                when 5 =>
                    read_adr_0_0_0 <= to_unsigned(1, write_adr_0_0_0'length);
                -- MemoryVariable(2, <b_asic.port.OutputPort object at 0x7f686c0e0780>, {<b_asic.port.InputPort object at 0x7f686c0e0960>: 4}, 'sym2p0_1.0')
                when 6 =>
                    read_adr_0_0_0 <= to_unsigned(0, write_adr_0_0_0'length);
                -- MemoryVariable(5, <b_asic.port.OutputPort object at 0x7f686c0e1310>, {<b_asic.port.InputPort object at 0x7f686c0e13b0>: 3}, 'sym2p4_0.1')
                when 8 =>
                    read_adr_0_0_0 <= to_unsigned(1, write_adr_0_0_0'length);
                -- MemoryVariable(6, <b_asic.port.OutputPort object at 0x7f686c0e0690>, {<b_asic.port.InputPort object at 0x7f686c0e1130>: 3}, 'sym2p3_1.1')
                when 9 =>
                    read_adr_0_0_0 <= to_unsigned(0, write_adr_0_0_0'length);
                -- MemoryVariable(7, <b_asic.port.OutputPort object at 0x7f686c0e0910>, {<b_asic.port.InputPort object at 0x7f686c0e0730>: 3}, 'sym2p0_0.1')
                when 10 =>
                    read_adr_0_0_0 <= to_unsigned(2, write_adr_0_0_0'length);
                when others =>
                    read_adr_0_0_0 <= (others => '-');
            end case;
    end process mem_read_address_proc;
end architecture rtl;

