--
-- This code was automatically generated by the B-ASIC toolbox.
-- Code generation timestamp: (2025-11-08 12:16:37.018125)
-- B-ASIC version: 0.1.0.dev825+unknown.g9c5aff44b
-- URL: https://github.com/b-asic-eda/b-asic
--

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
entity out0 is
    port (
        clk : in std_logic;
        schedule_cnt : in unsigned(3 downto 0);
        p_0_in : in signed(7 downto 0);
        p_0_out : out std_logic_vector(7 downto 0)
    );
end entity out0;

architecture rtl of out0 is
    signal op_0 : signed(7 downto 0);
    signal res_0 : std_logic_vector(7 downto 0);

begin
    op_0 <= p_0_in;
    p_0_out <= res_0;
    res_0 <= std_logic_vector(resize(signed(p_0_in), 8));


end architecture rtl;

