--
-- This code was automatically generated by the B-ASIC toolbox.
-- Code generation timestamp: (2025-11-05 22:58:23.906180)
-- B-ASIC version: 0.1.0.dev825+unknown.g9c5aff44b
-- URL: https://github.com/b-asic-eda/b-asic
--

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
entity sym2p0 is
    port (
        clk : in std_logic;
        schedule_cnt : in unsigned(3 downto 0);
        p_0_in : in signed(7 downto 0);
        p_1_in : in signed(7 downto 0);
        p_0_out : out signed(7 downto 0);
        p_1_out : out signed(7 downto 0)
    );
end entity sym2p0;

architecture rtl of sym2p0 is
    signal res_0_reg_0 : signed(7 downto 0) := (others => '0');
    signal res_1_reg_0 : signed(7 downto 0) := (others => '0');
    signal p_0_in_reg_0 : signed(7 downto 0) := (others => '0');
    signal p_1_in_reg_0 : signed(7 downto 0) := (others => '0');
    signal p_0_in_reg_1 : signed(7 downto 0) := (others => '0');
    signal p_1_in_reg_1 : signed(7 downto 0) := (others => '0');
    signal op_0 : signed(7 downto 0);
    signal op_1 : signed(7 downto 0);
    signal res_0 : signed(7 downto 0);
    signal res_1 : signed(7 downto 0);
    signal value : unsigned(7 downto 0);
    constant WL_VALUE_INT : integer := 1;
    signal u0 : signed(8 downto 0);
    signal mul_res : signed(u0'high + value'length downto 0);
    signal b0 : signed(mul_res'high + 1 downto 0);
    signal b1 : signed(mul_res'high + 1 downto 0);

begin
    process(clk)
    begin
        if rising_edge(clk) then
            res_0_reg_0 <= res_0;
            res_1_reg_0 <= res_1;
            p_0_in_reg_0 <= p_0_in;
            p_1_in_reg_0 <= p_1_in;
            p_0_in_reg_1 <= p_0_in_reg_0;
            p_1_in_reg_1 <= p_1_in_reg_0;
        end if;
    end process;
    op_0 <= p_0_in_reg_1;
    op_1 <= p_1_in_reg_1;
    with schedule_cnt select
        value <=
            b"11100101" when "0101",
            b"11100001" when "0000",
            b"11000101" when "0011",
            b"11100001" when "0010",
            b"11000101" when "1000",
            b"11110111" when "0001",
            b"10101001" when "0111",
            b"11100011" when "1010",
            b"11110111" when "0100",
            b"11000111" when "0110",
            b"01001001" when "1001",
            (others => '-') when others;

    p_0_out <= res_0_reg_0;
    p_1_out <= res_1_reg_0;
    u0 <= resize(op_1, 9) - resize(op_0, 9);
    mul_res <= u0 * signed(value);
    b0 <= (resize(op_0, op_0'length + 1 + 2) & "0000000") + resize(mul_res, b0'length);
    b1 <= (resize(op_1, op_1'length + 1 + 2) & "0000000") + resize(mul_res, b1'length);
    res_0 <= b1(b1'high - WL_VALUE_INT - 1 - 1 downto b1'high - WL_VALUE_INT - 1 - 1 - res_0'high);
    res_1 <= b0(b0'high - WL_VALUE_INT - 1 - 1 downto b0'high - WL_VALUE_INT - 1 - 1 - res_1'high);

end architecture rtl;

